import type { Metadata } from "next";
import { LegalLayout, P, UL, LI, Note } from "@/components/legal/LegalLayout";

export const metadata: Metadata = {
  title: "Terms & Conditions",
  description:
    "Please read these terms carefully before using Clarzo.ai. By using our platform, you agree to be bound by these terms.",
};

export default function TermsPage() {
  return (
    <LegalLayout
      title="Terms & Conditions"
      intro="Please read these terms carefully before using Clarzo.ai. By using our platform, you agree to be bound by these terms."
      updated="April 15, 2026"
      sections={[
        {
          id: "acceptance",
          label: "1. Acceptance of Terms",
          icon: "📜",
          content: (
            <>
              <P>
                By accessing or using Clarzo.ai (&quot;the Platform&quot;), you agree to be bound
                by these Terms and Conditions (&quot;Terms&quot;), our Privacy Policy, and any
                additional terms that may apply to specific features of the Platform.
              </P>
              <P>
                If you do not agree to these Terms, you must not use the Platform. If you are
                using the Platform on behalf of an organization, you represent that you have the
                authority to bind that organization to these Terms.
              </P>
              <P>
                You must be at least 18 years of age to use the Platform. By using Clarzo.ai, you
                confirm that you meet this age requirement.
              </P>
            </>
          ),
        },
        {
          id: "services",
          label: "2. Description of Services",
          icon: "⚡",
          content: (
            <>
              <P>Clarzo.ai provides an AI-powered wealth intelligence platform that offers:</P>
              <UL>
                <LI label="Portfolio Aggregation">Connecting and displaying financial data from multiple sources in a unified dashboard</LI>
                <LI label="AI-Powered Insights">Automated analysis of portfolio performance, risk, and allocation</LI>
                <LI label="ClarzoGPT">A conversational AI assistant that answers questions about your financial data</LI>
                <LI label="ClarzoGPT">A research tool providing company information based on publicly available financial data</LI>
                <LI label="Goal Tracking">Tools to map investments against personal financial goals</LI>
                <LI label="Spending Analysis">Categorization and analysis of bank transaction data</LI>
                <LI label="Expert Connect">A marketplace connecting users with SEBI-registered financial advisors</LI>
                <LI label="Stock Discovery">Educational tools for researching sectors and companies listed on BSE/NSE</LI>
              </UL>
              <P>
                We reserve the right to modify, suspend, or discontinue any part of the Platform at
                any time with reasonable notice.
              </P>
            </>
          ),
        },
        {
          id: "accounts",
          label: "3. User Accounts",
          icon: "👤",
          content: (
            <>
              <P>To access certain features, you must create an account. You agree to:</P>
              <UL>
                <LI>Provide accurate, current, and complete information during registration</LI>
                <LI>Maintain and update your information to keep it accurate</LI>
                <LI>Keep your login credentials secure and confidential</LI>
                <LI>Notify us immediately of any unauthorized access to your account</LI>
                <LI>Accept responsibility for all activities that occur under your account</LI>
              </UL>
              <P>
                We reserve the right to suspend or terminate accounts that violate these Terms or
                engage in fraudulent activity.
              </P>
            </>
          ),
        },
        {
          id: "advice",
          label: "4. Not Financial Advice",
          icon: "⚠️",
          content: (
            <>
              <Note title="Important Disclaimer">
                Clarzo.ai does not provide financial advice, investment advice, tax advice, or legal
                advice. All information, insights, suggestions, and recommendations provided
                through the Platform — including ClarzoGPT, ClarzoGPT, rebalancing suggestions, and
                stock discovery — are for educational and informational purposes only.
              </Note>
              <P>Specifically:</P>
              <UL>
                <LI>Rebalancing suggestions are educational in nature and should not be construed as investment recommendations</LI>
                <LI>ClarzoGPT and ClarzoGPT responses are generated by AI and may contain inaccuracies — always verify with official sources</LI>
                <LI>Stock Discovery content reflects publicly available data and does not constitute a buy/sell recommendation</LI>
                <LI>Past performance data displayed on the Platform does not guarantee future results</LI>
                <LI>You should consult a qualified financial advisor before making investment decisions</LI>
              </UL>
              <P>
                Clarzo.ai is an intelligence and aggregation layer — not a transaction platform. We
                do not execute trades, manage funds, or move money on your behalf.
              </P>
            </>
          ),
        },
        {
          id: "use",
          label: "5. Acceptable Use",
          icon: "✅",
          content: (
            <>
              <P>You agree to use the Platform only for lawful purposes. You must not:</P>
              <UL>
                <LI>Use the Platform to engage in any illegal activity or violate any applicable laws</LI>
                <LI>Attempt to gain unauthorized access to other users&apos; accounts or data</LI>
                <LI>Use automated tools (bots, scrapers) to extract data from the Platform without permission</LI>
                <LI>Reverse engineer, decompile, or disassemble any part of the Platform</LI>
                <LI>Upload malicious code, viruses, or any harmful content</LI>
                <LI>Share your account credentials with third parties or allow others to access your account</LI>
                <LI>Use ClarzoGPT or Stock Discovery data to provide unauthorized financial advisory services</LI>
                <LI>Misrepresent your identity or provide false information</LI>
              </UL>
            </>
          ),
        },
        {
          id: "ip",
          label: "6. Intellectual Property",
          icon: "©️",
          content: (
            <>
              <P>
                All content, features, and functionality of the Platform — including text,
                graphics, logos, icons, AI models, algorithms, software, and design — are owned by
                Clarzo.ai and protected by intellectual property laws.
              </P>
              <P>
                <strong className="text-ink">Your Data:</strong> You retain full ownership of your
                personal and financial data. By using the Platform, you grant us a limited,
                non-exclusive license to process your data solely for providing our services to
                you. This license ends when you delete your account.
              </P>
              <P>
                <strong className="text-ink">Feedback:</strong> If you provide suggestions, feature
                requests, or feedback, you grant us the right to use this feedback for product
                improvement without obligation to you.
              </P>
            </>
          ),
        },
        {
          id: "liability",
          label: "7. Limitation of Liability",
          icon: "⚖️",
          content: (
            <>
              <P>To the maximum extent permitted by law:</P>
              <UL>
                <LI>Clarzo.ai is provided &quot;as is&quot; and &quot;as available&quot; without warranties of any kind, express or implied</LI>
                <LI>We do not guarantee the accuracy, completeness, or timeliness of financial data displayed on the Platform</LI>
                <LI>We are not responsible for investment decisions you make based on information from the Platform</LI>
                <LI>We are not liable for any losses, damages, or costs arising from the use of the Platform, including but not limited to financial losses from investment decisions</LI>
                <LI>Our total liability for any claims arising from these Terms shall not exceed the amount you paid to us in the 12 months preceding the claim</LI>
              </UL>
              <P>
                <strong className="text-ink">Data Accuracy:</strong> While we strive for accuracy,
                financial data aggregated from third-party sources may contain delays, errors, or
                omissions. Always verify critical information with your broker, bank, or official
                sources.
              </P>
            </>
          ),
        },
        {
          id: "termination",
          label: "8. Termination",
          icon: "🚫",
          content: (
            <>
              <P>
                <strong className="text-ink">By You:</strong> You may delete your account at any
                time through the Platform settings. Upon deletion, all your personal and financial
                data will be permanently removed within 30 days, as outlined in our Privacy Policy.
              </P>
              <P>
                <strong className="text-ink">By Us:</strong> We may suspend or terminate your
                access if you violate these Terms, engage in fraudulent activity, or if we are
                required to do so by law. We will provide reasonable notice when possible.
              </P>
              <P>
                <strong className="text-ink">Effect of Termination:</strong> Upon termination, your
                right to access the Platform ceases immediately. Sections of these Terms that by
                their nature should survive (such as Limitation of Liability, Intellectual
                Property, and Governing Law) will continue to apply.
              </P>
            </>
          ),
        },
        {
          id: "changes",
          label: "9. Changes to Terms",
          icon: "🔄",
          content: (
            <>
              <P>We may update these Terms from time to time. When we make material changes:</P>
              <UL>
                <LI>We will notify you via email or a prominent notice on the Platform at least 30 days before changes take effect</LI>
                <LI>The &quot;Last updated&quot; date at the top of this page will be revised</LI>
                <LI>Continued use of the Platform after changes take effect constitutes acceptance of the updated Terms</LI>
                <LI>If you do not agree to the updated Terms, you should stop using the Platform and delete your account</LI>
              </UL>
            </>
          ),
        },
        {
          id: "law",
          label: "10. Governing Law & Disputes",
          icon: "🏛️",
          content: (
            <>
              <P>
                These Terms are governed by and construed in accordance with the laws of India. Any
                disputes arising from these Terms or the use of the Platform shall be subject to
                the exclusive jurisdiction of the courts in Mumbai, Maharashtra, India.
              </P>
              <P>
                Before initiating any legal proceedings, both parties agree to attempt resolution
                through good-faith negotiation for a period of at least 30 days.
              </P>
            </>
          ),
        },
        {
          id: "contact",
          label: "11. Contact",
          icon: "📬",
          content: (
            <>
              <P>If you have questions about these Terms & Conditions, please reach out:</P>
              <Note title="Clarzo.ai Legal Team">
                <div>
                  📧{" "}
                  <a href="mailto:contact@clarzo.ai" className="text-accent-deep hover:underline">
                    contact@clarzo.ai
                  </a>
                </div>
                <div className="mt-2 text-xs text-ink-muted">
                  For all legal, privacy, and general inquiries.
                </div>
              </Note>
            </>
          ),
        },
      ]}
    />
  );
}
